services:
  localstack:
    container_name: drive-lite-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"           # LocalStack Gateway
      - "4510-4559:4510-4559" # External service port range
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3,dynamodb,cognito-idp,iam,sts
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    networks:
      - drive-lite

networks:
  drive-lite:
    driver: bridge
