/**
 * Production environment configuration.
 * Automatically generated by scripts/configure-environment.mjs at build/deploy time.
 * DO NOT EDIT DIRECTLY.
 */
export const environment = {
  production: true,
  apiUrl: 'https://ob3elpuh3f.execute-api.us-east-1.amazonaws.com',
  cognitoEndpoint: '',
  cognitoUserPoolId: 'us-east-1_ldgalJHxI',
  cognitoClientId: '1vsakrvhq45at2d0cmajsic9bf',
  cognitoAuthDomain: '',
  s3Bucket: 'drivelitestack-storagefilesbucket28699c44-tnpemdvl31yx',
  hostingBucket: 'drivelitestack-frontendfrontendbucket428b8c09-38f1nflvcvjr',
  websiteUrl: 'http://drivelitestack-frontendfrontendbucket428b8c09-38f1nflvcvjr.s3-website-us-east-1.amazonaws.com',
  s3Region: 'us-east-1',
};
